import { getDatabase } from '../config/database.js';
import { ApiError } from '../utils/apiError.js';
function database() { const db = getDatabase(); if (!db) throw new ApiError(503, 'Database is not configured'); return db; }
function toCategory(row) { return { id: String(row.id), name: row.name, slug: row.slug, isActive: Boolean(row.is_active) }; }
function toItem(row) { return { id: String(row.id), name: row.name, slug: row.slug, description: row.description, imageUrl: row.image_url, mediaType: row.media_type || 'image', categoryId: row.category_id ? String(row.category_id) : null, category: row.category_name ? { id: String(row.category_id), name: row.category_name, slug: row.category_slug } : null, mealOfDay: row.meal_of_day, price: Number(row.price || 0), isAvailable: Boolean(row.is_available), isActive: Boolean(row.is_active), createdAt: row.created_at, updatedAt: row.updated_at }; }
function itemQuery(db) { return db('menu_items').leftJoin('menu_categories', 'menu_categories.id', 'menu_items.category_id').select('menu_items.*', 'menu_categories.name as category_name', 'menu_categories.slug as category_slug'); }
export async function listCategories() { return (await database()('menu_categories').where({ is_active: true }).orderBy('name')).map(toCategory); }
export async function createCategory(input) { const db = database(); const [id] = await db('menu_categories').insert({ name: input.name, slug: input.slug, is_active: input.isActive }); return toCategory(await db('menu_categories').where({ id }).first()); }
export async function updateCategory(id, input) { const db = database(); if (!(await db('menu_categories').where({ id }).update({ name: input.name, slug: input.slug, is_active: input.isActive }))) throw new ApiError(404, 'Menu category not found'); return toCategory(await db('menu_categories').where({ id }).first()); }
export async function deleteCategory(id) { if (!(await database()('menu_categories').where({ id }).del())) throw new ApiError(404, 'Menu category not found'); }
export async function listItems({ activeOnly = false } = {}) { const query = itemQuery(database()).orderBy('menu_items.name'); if (activeOnly) query.where({ 'menu_items.is_active': true, 'menu_items.is_available': true }); return (await query).map(toItem); }
export async function createItem(input) { const db = database(); const [id] = await db('menu_items').insert({ name: input.name, slug: input.slug, description: input.description, image_url: input.imageUrl || null, category_id: input.categoryId || null, meal_of_day: input.mealOfDay || null, price: input.price, is_available: input.isAvailable, is_active: input.isActive }); return toItem(await itemQuery(db).where('menu_items.id', id).first()); }
export async function updateItem(id, input) { const db = database(); if (!(await db('menu_items').where({ id }).update({ name: input.name, slug: input.slug, description: input.description, image_url: input.imageUrl || null, category_id: input.categoryId || null, meal_of_day: input.mealOfDay || null, price: input.price, is_available: input.isAvailable, is_active: input.isActive }))) throw new ApiError(404, 'Menu item not found'); return toItem(await itemQuery(db).where('menu_items.id', id).first()); }
export async function deleteItem(id) { if (!(await database()('menu_items').where({ id }).del())) throw new ApiError(404, 'Menu item not found'); }
export async function updateItemMedia(id, media) { const db = database(); if (!(await db('menu_items').where({ id }).update({ image_url: media.url, media_type: media.mediaType }))) throw new ApiError(404, 'Menu item not found'); return toItem(await itemQuery(db).where('menu_items.id', id).first()); }