import { Router } from 'express';
import { archiveVilla, assignReceptionist, assignReservationVilla, availabilityCalendar, checkAvailability, checkInReservation, checkOutReservation, confirmReservationBooking, createAmenity, createBooking, createPhoto, createVilla, estimatePricing, inviteStaffMember, listAccounts, listAllReservations, listAssignableReservationVillas, listCalendarVillas, listPublicVillas, listReservationNotifications, listReservations, listRevenueSummary, listVillas, resendReservationNotification, showPublicVilla, showReservation, showVilla, updateReservationStatus, updateVilla, updateVillaMap } from '../controllers/villaController.js';
import { createManagedPricingRule, deleteManagedPricingRule, listManagedPricingRules, updateManagedPricingRule } from '../controllers/pricingController.js';
import { optionalAuth, requireAuth, requireRole } from '../middleware/authMiddleware.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import { getConfig, updateConfig } from '../controllers/settingsController.js';
import { uploadPublicMap } from '../controllers/settingsController.js';
import { addChargeToReservation, collectReservationPaymentHandler, removeChargeFromReservation, showReservationStatement } from '../controllers/billingController.js';
import multer from 'multer';
import { uploadMedia } from '../controllers/villaController.js';
import { singleMediaUpload } from '../utils/mediaUpload.js';

const router = Router();
const upload = multer({ storage: multer.memoryStorage(), limits: { files: 20, fileSize: 50 * 1024 * 1024 } });
router.get('/public', asyncHandler(listPublicVillas));
router.get('/public/:villaId', asyncHandler(showPublicVilla));
router.get('/availability', asyncHandler(checkAvailability));
router.get('/availability-calendar', asyncHandler(availabilityCalendar));
router.get('/pricing', asyncHandler(estimatePricing));
router.get('/config/public', asyncHandler(getConfig));
router.post('/bookings', optionalAuth, asyncHandler(createBooking));
router.use(asyncHandler(requireAuth));
router.get('/revenue', requireRole('admin', 'host'), asyncHandler(listRevenueSummary));
router.patch('/:villaId/archive', asyncHandler(archiveVilla));
router.patch('/:villaId/map-position', asyncHandler(updateVillaMap));
router.get('/config', asyncHandler(getConfig));
router.patch('/config', requireRole('admin'), asyncHandler(updateConfig));
router.post('/config/public-map', requireRole('admin'), singleMediaUpload, asyncHandler(uploadPublicMap));
router.get('/', asyncHandler(listVillas));
router.post('/', requireRole('admin'), asyncHandler(createVilla));
router.post('/staff', requireRole('admin'), asyncHandler(inviteStaffMember));
router.get('/accounts', requireRole('admin'), asyncHandler(listAccounts));
router.get('/calendar', requireRole('admin', 'host', 'receptionist'), asyncHandler(listCalendarVillas));
router.get('/pricing-rules', requireRole('admin', 'host'), asyncHandler(listManagedPricingRules));
router.post('/pricing-rules', requireRole('admin', 'host'), asyncHandler(createManagedPricingRule));
router.put('/pricing-rules/:ruleId', requireRole('admin', 'host'), asyncHandler(updateManagedPricingRule));
router.delete('/pricing-rules/:ruleId', requireRole('admin', 'host'), asyncHandler(deleteManagedPricingRule));
router.get('/reservations', requireRole('admin', 'host', 'receptionist'), asyncHandler(listAllReservations));
router.get('/notifications', requireRole('admin', 'host', 'receptionist'), asyncHandler(listReservationNotifications));
router.get('/reservations/:reservationId/assignable-villas', requireRole('admin', 'receptionist'), asyncHandler(listAssignableReservationVillas));
router.get('/reservations/:reservationId/statement', requireRole('admin', 'host', 'receptionist'), asyncHandler(showReservationStatement));
router.post('/reservations/:reservationId/charges', requireRole('admin', 'host', 'receptionist'), asyncHandler(addChargeToReservation));
router.delete('/reservations/:reservationId/charges/:chargeId', requireRole('admin', 'host', 'receptionist'), asyncHandler(removeChargeFromReservation));
router.post('/reservations/:reservationId/payments', requireRole('admin', 'host', 'receptionist'), asyncHandler(collectReservationPaymentHandler));
router.post('/reservations/:reservationId/confirm', requireRole('admin', 'receptionist'), asyncHandler(confirmReservationBooking));
router.post('/reservations/:reservationId/check-in', requireRole('admin', 'receptionist'), asyncHandler(checkInReservation));
router.post('/reservations/:reservationId/check-out', requireRole('admin', 'receptionist'), asyncHandler(checkOutReservation));
router.post('/reservations/:reservationId/emails/:emailType/resend', requireRole('admin', 'receptionist'), asyncHandler(resendReservationNotification));
router.post('/reservations/:reservationId/state', requireRole('admin', 'receptionist'), asyncHandler(updateReservationStatus));
router.get('/reservations/:reservationId', requireRole('admin', 'host', 'receptionist'), asyncHandler(showReservation));
router.get('/:villaId', asyncHandler(showVilla));
router.put('/:villaId', requireRole('admin', 'host'), asyncHandler(updateVilla));
router.post('/:villaId/amenities', requireRole('admin', 'host'), asyncHandler(createAmenity));
router.post('/:villaId/photos', requireRole('admin', 'host'), asyncHandler(createPhoto));
router.post('/:villaId/media', requireRole('admin', 'host'), upload.array('media', 20), asyncHandler(uploadMedia));
router.post('/:villaId/receptionists', requireRole('admin'), asyncHandler(assignReceptionist));
router.get('/:villaId/reservations', requireRole('admin', 'host', 'receptionist'), asyncHandler(listReservations));
router.patch('/reservations/:reservationId/assign', requireRole('admin', 'receptionist'), asyncHandler(assignReservationVilla));
router.patch('/:villaId/reservations/:reservationId/status', requireRole('admin', 'host', 'receptionist'), asyncHandler(updateReservationStatus));

export default router;
